use std::{
    path::{Path, PathBuf},
    process::Stdio,
    time::{SystemTime, UNIX_EPOCH},
};

use tokio::process::Command;

const LEGACY_GENERATED_HEADER: &str =
    "-- Generated by `yap setup hyprland`; local edits are replaced.\n";
const LEGACY_INCLUDE_MARKER: &str = "-- Yap dictation hotkey\nrequire(\"yap-dictation\")";
const SYSTEMD_ENABLE_ARGUMENTS: &[&str] = &[
    "--user",
    "enable",
    "yap.service",
    "yap-overlay.service",
];
const SYSTEMD_RESTART_ARGUMENTS: &[&str] = &[
    "--user",
    "restart",
    "yap.service",
    "yap-overlay.service",
];

#[derive(Debug, Eq, PartialEq)]
pub struct SetupOutcome {
    pub removed_legacy_config: Option<PathBuf>,
    pub main_backup: Option<PathBuf>,
    pub preserved_config: Option<PathBuf>,
}

/// Starts Yap without claiming a Hyprland keybinding.
///
/// Older development builds installed a Right-Super binding. When that exact managed binding is
/// still present, setup backs up the main config, removes the include, removes the generated file,
/// and reloads Hyprland. Unmanaged files are preserved.
pub async fn hyprland() -> Result<SetupOutcome, String> {
    run("systemctl", SYSTEMD_ENABLE_ARGUMENTS)
        .await
        .map_err(|error| format!("Yap's user services could not be enabled: {error}"))?;
    run("systemctl", SYSTEMD_RESTART_ARGUMENTS)
        .await
        .map_err(|error| format!("Yap's user services did not restart: {error}"))?;

    let cleanup = remove_legacy_binding(&config_home().join("hypr"))?;
    if cleanup.main_backup.is_some() {
        run("hyprctl", &["reload"]).await.map_err(|error| {
            format!("legacy binding was removed, but Hyprland did not reload: {error}")
        })?;
    }

    Ok(cleanup)
}

fn remove_legacy_binding(hypr_dir: &Path) -> Result<SetupOutcome, String> {
    let main_config = hypr_dir.join("hyprland.lua");
    let generated_config = hypr_dir.join("yap-dictation.lua");
    let mut main_backup = None;

    if main_config.is_file() {
        let content = std::fs::read_to_string(&main_config)
            .map_err(|error| format!("could not read {}: {error}", main_config.display()))?;
        if content.contains(LEGACY_INCLUDE_MARKER) {
            let backup = backup_path(&main_config)?;
            std::fs::copy(&main_config, &backup).map_err(|error| {
                format!(
                    "could not back up {} to {}: {error}",
                    main_config.display(),
                    backup.display()
                )
            })?;
            let content = remove_legacy_include(&content);
            atomic_write(&main_config, &content)?;
            main_backup = Some(backup);
        }
    }

    let mut removed_legacy_config = None;
    let mut preserved_config = None;
    if generated_config.is_file() {
        let content = std::fs::read_to_string(&generated_config).map_err(|error| {
            format!("could not inspect {}: {error}", generated_config.display())
        })?;
        if main_backup.is_some() && content.starts_with(LEGACY_GENERATED_HEADER) {
            std::fs::remove_file(&generated_config).map_err(|error| {
                format!(
                    "could not remove legacy config {}: {error}",
                    generated_config.display()
                )
            })?;
            removed_legacy_config = Some(generated_config);
        } else {
            preserved_config = Some(generated_config);
        }
    }

    Ok(SetupOutcome {
        removed_legacy_config,
        main_backup,
        preserved_config,
    })
}

fn remove_legacy_include(content: &str) -> String {
    let surrounded = format!("\n{LEGACY_INCLUDE_MARKER}\n");
    if content.contains(&surrounded) {
        content.replacen(&surrounded, "", 1)
    } else {
        content.replacen(LEGACY_INCLUDE_MARKER, "", 1)
    }
}

fn atomic_write(path: &Path, content: &str) -> Result<(), String> {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("invalid configuration path: {}", path.display()))?;
    let temporary = path.with_file_name(format!(".{file_name}.yap-{}.tmp", std::process::id()));
    std::fs::write(&temporary, content)
        .map_err(|error| format!("could not write {}: {error}", temporary.display()))?;
    std::fs::rename(&temporary, path)
        .map_err(|error| format!("could not replace {}: {error}", path.display()))
}

fn backup_path(path: &Path) -> Result<PathBuf, String> {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|error| format!("system clock is before the Unix epoch: {error}"))?
        .as_secs();
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("invalid configuration path: {}", path.display()))?;
    Ok(path.with_file_name(format!("{file_name}.yap-backup-{timestamp}")))
}

async fn run(program: &str, arguments: &[&str]) -> Result<(), String> {
    let status = Command::new(program)
        .args(arguments)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .await
        .map_err(|error| format!("could not run {program}: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{program} exited with {status}"))
    }
}

fn config_home() -> PathBuf {
    std::env::var_os("XDG_CONFIG_HOME").map_or_else(
        || {
            std::env::var_os("HOME").map_or_else(
                || PathBuf::from(".config"),
                |home| PathBuf::from(home).join(".config"),
            )
        },
        PathBuf::from,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temporary_directory(name: &str) -> PathBuf {
        let directory = std::env::temp_dir().join(format!(
            "yap-setup-test-{name}-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("valid clock")
                .as_nanos()
        ));
        std::fs::create_dir_all(&directory).expect("create test directory");
        directory
    }

    #[test]
    fn legacy_right_super_binding_is_backed_up_and_removed() {
        let directory = temporary_directory("legacy-cleanup");
        let main = directory.join("hyprland.lua");
        let generated = directory.join("yap-dictation.lua");
        let original_main = format!("hl.config({{}})\n\n{LEGACY_INCLUDE_MARKER}\n");
        std::fs::write(&main, &original_main).expect("seed main config");
        std::fs::write(
            &generated,
            format!("{LEGACY_GENERATED_HEADER}legacy right-super bindings\n"),
        )
        .expect("seed generated config");

        let outcome = remove_legacy_binding(&directory).expect("remove managed legacy binding");

        assert_eq!(outcome.removed_legacy_config, Some(generated.clone()));
        assert!(!generated.exists());
        assert_eq!(
            std::fs::read_to_string(&main).expect("read cleaned config"),
            "hl.config({})\n"
        );
        assert_eq!(
            std::fs::read_to_string(outcome.main_backup.expect("backup created"))
                .expect("read backup"),
            original_main
        );
    }

    #[test]
    fn unmanaged_config_is_preserved() {
        let directory = temporary_directory("unmanaged");
        let generated = directory.join("yap-dictation.lua");
        std::fs::write(&generated, "-- user-owned\n").expect("seed user config");

        let outcome = remove_legacy_binding(&directory).expect("inspect legacy config");

        assert_eq!(outcome.removed_legacy_config, None);
        assert_eq!(outcome.main_backup, None);
        assert_eq!(outcome.preserved_config, Some(generated.clone()));
        assert!(generated.exists());
    }

    #[test]
    fn setup_restarts_both_services_after_enabling_them() {
        assert_eq!(
            SYSTEMD_ENABLE_ARGUMENTS,
            [
                "--user",
                "enable",
                "yap.service",
                "yap-overlay.service"
            ]
        );
        assert_eq!(
            SYSTEMD_RESTART_ARGUMENTS,
            [
                "--user",
                "restart",
                "yap.service",
                "yap-overlay.service"
            ]
        );
    }
}
