use std::{
    path::{Path, PathBuf},
    process::Stdio,
    time::{SystemTime, UNIX_EPOCH},
};

use tokio::process::Command;

const GENERATED_HEADER: &str = "-- Generated by `yap setup hyprland`; local edits are replaced.\n";
const INCLUDE_MARKER: &str = "-- Yap dictation hotkey\nrequire(\"yap-dictation\")";

#[derive(Debug, Eq, PartialEq)]
pub struct SetupOutcome {
    pub generated_config: PathBuf,
    pub main_config: PathBuf,
    pub main_backup: Option<PathBuf>,
}

pub async fn hyprland() -> Result<SetupOutcome, String> {
    let hypr_dir = config_home().join("hypr");
    let main_config = hypr_dir.join("hyprland.lua");
    if !main_config.is_file() {
        return Err(format!(
            "Hyprland Lua config was not found at {}",
            main_config.display()
        ));
    }

    let generated_config = hypr_dir.join("yap-dictation.lua");
    write_generated(&generated_config)?;
    let main_backup = add_include(&main_config)?;

    run("systemctl", &["--user", "enable", "--now", "yap.service"])
        .await
        .map_err(|error| {
            format!("configuration was written, but yap.service did not start: {error}")
        })?;
    run("hyprctl", &["reload"]).await.map_err(|error| {
        format!("configuration was written, but Hyprland did not reload: {error}")
    })?;

    Ok(SetupOutcome {
        generated_config,
        main_config,
        main_backup,
    })
}

fn write_generated(path: &Path) -> Result<(), String> {
    if path.exists() {
        let existing = std::fs::read_to_string(path)
            .map_err(|error| format!("could not inspect {}: {error}", path.display()))?;
        if !existing.starts_with(GENERATED_HEADER) {
            return Err(format!(
                "refusing to replace unmanaged config {}; move it and retry",
                path.display()
            ));
        }
    }

    let content = format!(
        "{GENERATED_HEADER}hl.bind(\"SUPER + SUPER_R\", hl.dsp.exec_cmd(\"yapctl press dictation\"), {{ description = \"Yap: hold to dictate\" }})\nhl.bind(\"SUPER + SUPER_R\", hl.dsp.exec_cmd(\"yapctl release dictation\"), {{ release = true, description = \"Yap: finish dictation\" }})\n"
    );
    atomic_write(path, &content)
}

fn add_include(main_config: &Path) -> Result<Option<PathBuf>, String> {
    let mut content = std::fs::read_to_string(main_config)
        .map_err(|error| format!("could not read {}: {error}", main_config.display()))?;
    if content.contains(INCLUDE_MARKER) || content.contains("require(\"yap-dictation\")") {
        return Ok(None);
    }

    let backup = backup_path(main_config)?;
    std::fs::copy(main_config, &backup).map_err(|error| {
        format!(
            "could not back up {} to {}: {error}",
            main_config.display(),
            backup.display()
        )
    })?;
    if !content.ends_with('\n') {
        content.push('\n');
    }
    content.push('\n');
    content.push_str(INCLUDE_MARKER);
    content.push('\n');
    atomic_write(main_config, &content)?;
    Ok(Some(backup))
}

fn atomic_write(path: &Path, content: &str) -> Result<(), String> {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("invalid configuration path: {}", path.display()))?;
    let temporary = path.with_file_name(format!(".{file_name}.yap-{}.tmp", std::process::id()));
    std::fs::write(&temporary, content)
        .map_err(|error| format!("could not write {}: {error}", temporary.display()))?;
    std::fs::rename(&temporary, path)
        .map_err(|error| format!("could not replace {}: {error}", path.display()))
}

fn backup_path(path: &Path) -> Result<PathBuf, String> {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|error| format!("system clock is before the Unix epoch: {error}"))?
        .as_secs();
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("invalid configuration path: {}", path.display()))?;
    Ok(path.with_file_name(format!("{file_name}.yap-backup-{timestamp}")))
}

async fn run(program: &str, arguments: &[&str]) -> Result<(), String> {
    let status = Command::new(program)
        .args(arguments)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .await
        .map_err(|error| format!("could not run {program}: {error}"))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!("{program} exited with {status}"))
    }
}

fn config_home() -> PathBuf {
    std::env::var_os("XDG_CONFIG_HOME").map_or_else(
        || {
            std::env::var_os("HOME").map_or_else(
                || PathBuf::from(".config"),
                |home| PathBuf::from(home).join(".config"),
            )
        },
        PathBuf::from,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temporary_directory(name: &str) -> PathBuf {
        let directory = std::env::temp_dir().join(format!(
            "yap-setup-test-{name}-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("valid clock")
                .as_nanos()
        ));
        std::fs::create_dir_all(&directory).expect("create test directory");
        directory
    }

    #[test]
    fn generated_binding_has_both_right_super_edges() {
        let directory = temporary_directory("bindings");
        let path = directory.join("yap-dictation.lua");

        write_generated(&path).expect("generate config");
        let content = std::fs::read_to_string(path).expect("read config");

        assert!(content.contains("yapctl press dictation"));
        assert!(content.contains("yapctl release dictation"));
        assert!(content.contains("release = true"));
    }

    #[test]
    fn include_edit_is_backed_up_and_idempotent() {
        let directory = temporary_directory("include");
        let path = directory.join("hyprland.lua");
        std::fs::write(&path, "hl.config({})\n").expect("seed config");

        let backup = add_include(&path)
            .expect("add include")
            .expect("backup was created");
        assert_eq!(
            std::fs::read_to_string(backup).expect("read backup"),
            "hl.config({})\n"
        );
        assert!(
            std::fs::read_to_string(&path)
                .expect("read edited config")
                .contains(INCLUDE_MARKER)
        );
        assert_eq!(add_include(&path).expect("repeat include"), None);
    }
}
