#!/usr/bin/env bash
# PROTOTYPE ONLY — disposable Linux feasibility probe for Yap.

set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
SCRIPT_PATH="$SCRIPT_DIR/run.sh"
RUNTIME_BASE="${XDG_RUNTIME_DIR:-/tmp}"
RUNTIME_DIR="$RUNTIME_BASE/yap-linux-spike-${UID}"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/yap-prototype"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/yap"
HYPR_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
if [[ -f "$HYPR_CONFIG_DIR/hyprland.lua" ]]; then
    HOTKEY_CONFIG="$CONFIG_DIR/prototype-hyprland.lua"
    HYPR_CONFIG_STYLE="lua"
else
    HOTKEY_CONFIG="$CONFIG_DIR/prototype-hyprland.conf"
    HYPR_CONFIG_STYLE="legacy"
fi
EVENT_LOG="$RUNTIME_DIR/hotkey.events"
RESULT_LOG="$RUNTIME_DIR/results.tsv"
SERVER_LOG="$RUNTIME_DIR/whisper-server.log"
BENCH_LOG="$RUNTIME_DIR/benchmark.tsv"
E2E_LOG="$RUNTIME_DIR/end-to-end.tsv"
AUDIO_FILE="$RUNTIME_DIR/dictation.wav"
MODEL_NAME="large-v3-turbo-q5_0"
MODEL_FILE="$DATA_DIR/models/ggml-$MODEL_NAME.bin"
MODEL_URL="https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-$MODEL_NAME.bin"
MODEL_SHA256="394221709cd5ad1f40c46e6031ca61bce88931e6e088c188294c6d5a55ffa7e2"
SERVER_PID=""
RECORDER_PID=""

ensure_runtime() {
    mkdir -p "$RUNTIME_DIR"
    touch "$EVENT_LOG" "$RESULT_LOG"
}

event_command() {
    local edge="${1:-}"
    case "$edge" in
        press|release) ;;
        *) exit 2 ;;
    esac
    ensure_runtime
    printf '%s\t%s\n' "$(date +%s%N)" "$edge" >> "$EVENT_LOG"
}

# Keep compositor-triggered event recording fast and silent.
if [[ "${1:-}" == "event" ]]; then
    event_command "${2:-}"
    exit $?
fi

ensure_runtime

section() {
    printf '\n\033[1;36m%s\033[0m\n' "$1"
}

record_result() {
    local phase="$1"
    local status="$2"
    local detail="${3//$'\n'/ }"
    detail="${detail//$'\t'/ }"
    printf '%s\t%s\t%s\t%s\n' "$(date --iso-8601=seconds)" "$phase" "$status" "$detail" >> "$RESULT_LOG"
    printf '[%s] %s: %s\n' "$status" "$phase" "$detail"
}

show_state() {
    section "Prototype state"
    printf 'Runtime: %s\n' "$RUNTIME_DIR"
    printf 'Model:   %s\n' "$MODEL_FILE"
    printf 'Binding: %s\n\n' "$HOTKEY_CONFIG"
    if [[ -s "$RESULT_LOG" ]]; then
        column -t -s $'\t' "$RESULT_LOG" 2>/dev/null || tail -n 30 "$RESULT_LOG"
    else
        printf 'No probe results yet.\n'
    fi
}

doctor() {
    section "Environment and dependency check"
    local required=(hyprctl busctl pw-record whisper-server curl python3 sha256sum wtype wl-copy wl-paste)
    local missing=()
    local command_name

    for command_name in "${required[@]}"; do
        if ! command -v "$command_name" >/dev/null 2>&1; then
            missing+=("$command_name")
        fi
    done

    printf 'Session:  %s\n' "${XDG_SESSION_TYPE:-unknown}"
    printf 'Desktop:  %s\n' "${XDG_CURRENT_DESKTOP:-unknown}"
    printf 'Wayland:  %s\n' "${WAYLAND_DISPLAY:-missing}"
    printf 'Hyprland: %s\n' "${HYPRLAND_INSTANCE_SIGNATURE:-missing}"
    printf 'Config:   %s\n' "$HYPR_CONFIG_STYLE"

    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl version 2>/dev/null | sed -n '1,4p' || true
    fi
    if command -v nvidia-smi >/dev/null 2>&1; then
        nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv,noheader 2>/dev/null || true
    fi
    if command -v pacman >/dev/null 2>&1; then
        pacman -Q whisper-cpp ggml-cuda pipewire-audio wtype wl-clipboard 2>/dev/null || true
    fi

    if command -v busctl >/dev/null 2>&1 && busctl --user introspect \
        org.freedesktop.portal.Desktop \
        /org/freedesktop/portal/desktop \
        org.freedesktop.portal.GlobalShortcuts >/dev/null 2>&1; then
        record_result "global-shortcuts-portal" "PASS" "Interface is exposed on the session bus"
    else
        record_result "global-shortcuts-portal" "WARN" "Interface was not discoverable"
    fi

    if ((${#missing[@]})); then
        record_result "dependencies" "FAIL" "Missing: ${missing[*]}"
        printf '\nInstall the probe dependencies, then rerun:\n\n'
        printf '  sudo pacman -S --needed pipewire-audio whisper-cpp ggml-cuda wtype wl-clipboard curl python\n'
        return 1
    fi

    if [[ "${XDG_SESSION_TYPE:-}" != "wayland" || -z "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
        record_result "session" "FAIL" "Run this from inside the target Hyprland session"
        return 1
    fi

    record_result "dependencies" "PASS" "All required commands are available"
    record_result "session" "PASS" "Hyprland Wayland session detected"
}

generate_hotkey_config() {
    section "Generate the Right Super probe binding"
    mkdir -p "$CONFIG_DIR"
    if [[ "$HYPR_CONFIG_STYLE" == "lua" ]]; then
        {
            printf '%s\n' '-- PROTOTYPE ONLY — generated by Yap Linux spike.'
            printf '%s\n' '-- Remove this file and its require() line after the spike.'
            printf 'hl.bind("SUPER + SUPER_R", hl.dsp.exec_cmd("%s event press"))\n' "$SCRIPT_PATH"
            printf 'hl.bind("SUPER + SUPER_R", hl.dsp.exec_cmd("%s event release"), { release = true })\n' "$SCRIPT_PATH"
        } > "$HOTKEY_CONFIG"
    else
        {
            printf '# PROTOTYPE ONLY — generated by Yap Linux spike.\n'
            printf '# Remove this file and its source line after the spike.\n'
            printf 'bind = SUPER, SUPER_R, exec, %s event press\n' "$SCRIPT_PATH"
            printf 'bindr = SUPER, SUPER_R, exec, %s event release\n' "$SCRIPT_PATH"
        } > "$HOTKEY_CONFIG"
    fi

    record_result "hotkey-config" "READY" "Generated $HOTKEY_CONFIG"
    printf '\nAdd this exact line to your Hyprland configuration:\n\n'
    if [[ "$HYPR_CONFIG_STYLE" == "lua" ]]; then
        printf '  require("%s")\n\n' "$HOTKEY_CONFIG"
    else
        printf '  source = %s\n\n' "$HOTKEY_CONFIG"
    fi
    printf 'Then run: hyprctl reload\n'
}

test_hotkey() {
    section "Right Super press/release test"
    : > "$EVENT_LOG"
    printf 'Press and release Right Super three times within the next 20 seconds.\n'
    printf 'Make one press a deliberate ~1 second hold.\n\n'

    local attempts=0
    local count=0
    while ((attempts < 200)); do
        count="$(wc -l < "$EVENT_LOG")"
        if ((count >= 6)); then
            break
        fi
        sleep 0.1
        attempts=$((attempts + 1))
    done

    if ! python3 - "$EVENT_LOG" <<'PY'
import pathlib
import sys

events = []
for line in pathlib.Path(sys.argv[1]).read_text().splitlines():
    timestamp, edge = line.split("\t", 1)
    events.append((int(timestamp), edge))

print(f"Observed {len(events)} edge(s):")
for timestamp, edge in events:
    print(f"  {timestamp}  {edge}")

if len(events) < 6:
    raise SystemExit(1)

sample = events[:6]
expected = ["press", "release"] * 3
if [edge for _, edge in sample] != expected:
    print("Edges were not an alternating press/release sequence.")
    raise SystemExit(1)

for index in range(0, 6, 2):
    duration_ms = (sample[index + 1][0] - sample[index][0]) / 1_000_000
    print(f"  hold {index // 2 + 1}: {duration_ms:.1f} ms")
PY
    then
        record_result "right-super-edges" "FAIL" "Did not receive three reliable press/release pairs"
        return 1
    fi

    record_result "right-super-edges" "PASS" "Received three ordered press/release pairs"
}

ensure_model() {
    mkdir -p "$(dirname "$MODEL_FILE")"

    if [[ -f "$MODEL_FILE" ]]; then
        if printf '%s  %s\n' "$MODEL_SHA256" "$MODEL_FILE" | sha256sum --check --status; then
            record_result "asr-model" "PASS" "Verified existing $MODEL_NAME"
            return 0
        fi
        record_result "asr-model" "FAIL" "Existing model checksum is invalid"
        return 1
    fi

    printf '\nThe probe needs the 547 MiB %s model.\n' "$MODEL_NAME"
    printf 'It will be downloaded only after this confirmation and verified with SHA-256.\n'
    read -r -p 'Download it now? [y/N] ' answer
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
        record_result "asr-model" "BLOCKED" "User declined explicit model download"
        return 1
    fi

    local partial="$MODEL_FILE.part"
    if ! curl -L --fail --retry 3 --progress-bar "$MODEL_URL" -o "$partial"; then
        rm -f "$partial"
        record_result "asr-model" "FAIL" "Download failed"
        return 1
    fi
    if ! printf '%s  %s\n' "$MODEL_SHA256" "$partial" | sha256sum --check --status; then
        rm -f "$partial"
        record_result "asr-model" "FAIL" "Downloaded model checksum mismatch"
        return 1
    fi
    mv "$partial" "$MODEL_FILE"
    record_result "asr-model" "PASS" "Downloaded and verified $MODEL_NAME"
}

capture_audio() {
    section "PipeWire microphone capture"
    rm -f "$AUDIO_FILE"
    printf 'Press Enter to start. Speak a normal 5–10 second dictation, then press Enter to stop.\n'
    read -r

    pw-record --rate=16000 --channels=1 --channel-map=mono --format=s16 "$AUDIO_FILE" \
        >"$RUNTIME_DIR/pw-record.log" 2>&1 &
    RECORDER_PID=$!
    sleep 0.5
    if ! kill -0 "$RECORDER_PID" 2>/dev/null; then
        record_result "pipewire-capture" "FAIL" "pw-record exited before capture began"
        return 1
    fi

    printf 'Recording… press Enter to stop.\n'
    read -r
    kill -INT "$RECORDER_PID" 2>/dev/null || true
    wait "$RECORDER_PID" 2>/dev/null || true
    RECORDER_PID=""

    if [[ ! -s "$AUDIO_FILE" ]] || (( $(stat -c %s "$AUDIO_FILE") <= 44 )); then
        record_result "pipewire-capture" "FAIL" "No usable WAV data was written"
        return 1
    fi
    record_result "pipewire-capture" "PASS" "Captured $(stat -c %s "$AUDIO_FILE") bytes at requested 16 kHz mono"
}

stop_server() {
    if [[ -n "$SERVER_PID" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    SERVER_PID=""
}

stop_children() {
    stop_server
    if [[ -n "$RECORDER_PID" ]] && kill -0 "$RECORDER_PID" 2>/dev/null; then
        kill -INT "$RECORDER_PID" 2>/dev/null || true
        wait "$RECORDER_PID" 2>/dev/null || true
    fi
    RECORDER_PID=""
}

end_to_end_benchmark() {
    local port="$1"
    section "Warm release-to-insertion benchmark"
    printf 'This will transcribe the captured WAV five times and type each result into one scratch field.\n'
    printf 'Every inserted line starts with # so an accidental shell target remains a comment.\n'
    read -r -p 'Run the end-to-end insertion benchmark? [Y/n] ' answer
    if [[ "$answer" =~ ^[Nn]$ ]]; then
        record_result "warm-e2e" "BLOCKED" "User skipped the insertion latency measurement"
        return 0
    fi

    printf 'Press Enter, then focus a non-password scratch field within five seconds.\n'
    read -r
    sleep 5
    : > "$E2E_LOG"

    local iteration
    for iteration in 1 2 3 4 5; do
        local response="$RUNTIME_DIR/e2e-$iteration.json"
        local started_ns
        local finished_ns
        local transcript
        local elapsed
        started_ns="$(date +%s%N)"
        if ! curl -sS \
            -o "$response" \
            -H 'Content-Type: multipart/form-data' \
            -F "file=@$AUDIO_FILE" \
            -F 'temperature=0.0' \
            -F 'temperature_inc=0.0' \
            -F 'response_format=json' \
            "http://127.0.0.1:$port/inference"; then
            record_result "warm-e2e" "FAIL" "Inference request $iteration failed"
            return 1
        fi
        transcript="$(python3 - "$response" <<'PY'
import json
import pathlib
import sys
payload = json.loads(pathlib.Path(sys.argv[1]).read_text())
print(payload.get("text") or payload.get("transcription") or payload)
PY
)"
        transcript="$(printf '%s' "$transcript" | tr '\n' ' ')"
        printf '# Yap E2E %s: %s' "$iteration" "$transcript" | wtype -d 1 -
        wtype -P Return -p Return
        finished_ns="$(date +%s%N)"
        elapsed="$(python3 - "$started_ns" "$finished_ns" <<'PY'
import sys
print(f"{(int(sys.argv[2]) - int(sys.argv[1])) / 1_000_000_000:.6f}")
PY
)"
        printf '%s\t%s\n' "$iteration" "$elapsed" >> "$E2E_LOG"
    done

    local metrics
    local p95
    metrics="$(python3 - "$E2E_LOG" <<'PY'
import math
import pathlib
import statistics
import sys
values = [float(line.split("\t")[1]) for line in pathlib.Path(sys.argv[1]).read_text().splitlines()]
ordered = sorted(values)
p95 = ordered[max(0, math.ceil(0.95 * len(ordered)) - 1)]
print(f"p50={statistics.median(values):.3f}s p95={p95:.3f}s min={min(values):.3f}s max={max(values):.3f}s")
PY
)"
    p95="$(python3 - "$E2E_LOG" <<'PY'
import math
import pathlib
import sys
values = sorted(float(line.split("\t")[1]) for line in pathlib.Path(sys.argv[1]).read_text().splitlines())
print(values[max(0, math.ceil(0.95 * len(values)) - 1)])
PY
)"
    if python3 - "$p95" <<'PY'
import sys
raise SystemExit(0 if float(sys.argv[1]) <= 3.0 else 1)
PY
    then
        record_result "warm-e2e" "PASS" "$metrics"
    else
        record_result "warm-e2e" "FAIL" "$metrics (p95 exceeds 3 seconds)"
    fi
    printf 'Return to this terminal to continue.\n'
}

start_server() {
    local port="$1"
    rm -f "$SERVER_LOG"
    whisper-server \
        --model "$MODEL_FILE" \
        --language auto \
        --host 127.0.0.1 \
        --port "$port" \
        --no-context \
        --no-timestamps \
        >"$SERVER_LOG" 2>&1 &
    SERVER_PID=$!

    local attempt=0
    while ((attempt < 600)); do
        if ! kill -0 "$SERVER_PID" 2>/dev/null; then
            record_result "whisper-server" "FAIL" "Server exited while loading the model; inspect $SERVER_LOG"
            return 1
        fi
        if curl -sS -o /dev/null "http://127.0.0.1:$port/" 2>/dev/null; then
            record_result "whisper-server" "PASS" "Warm context ready on loopback port $port"
            return 0
        fi
        sleep 0.25
        attempt=$((attempt + 1))
    done

    record_result "whisper-server" "FAIL" "Model did not become ready within 150 seconds"
    return 1
}

benchmark() {
    section "Warm whisper.cpp latency benchmark"
    ensure_model || return 1
    if [[ ! -s "$AUDIO_FILE" ]]; then
        capture_audio || return 1
    fi

    local port
    port="$(python3 - <<'PY'
import socket
with socket.socket() as sock:
    sock.bind(("127.0.0.1", 0))
    print(sock.getsockname()[1])
PY
)"
    start_server "$port" || return 1

    : > "$BENCH_LOG"
    local iteration
    for iteration in 0 1 2 3 4 5; do
        local response="$RUNTIME_DIR/inference-$iteration.json"
        local seconds
        seconds="$(curl -sS \
            -o "$response" \
            -w '%{time_total}' \
            -H 'Content-Type: multipart/form-data' \
            -F "file=@$AUDIO_FILE" \
            -F 'temperature=0.0' \
            -F 'temperature_inc=0.0' \
            -F 'response_format=json' \
            "http://127.0.0.1:$port/inference")" || {
                stop_server
                record_result "warm-asr" "FAIL" "Inference request failed"
                return 1
            }

        local transcript
        transcript="$(python3 - "$response" <<'PY'
import json
import pathlib
import sys

payload = json.loads(pathlib.Path(sys.argv[1]).read_text())
if isinstance(payload, dict):
    print(payload.get("text") or payload.get("transcription") or payload)
else:
    print(payload)
PY
)"
        if ((iteration == 0)); then
            printf 'Warm-up: %ss — %s\n' "$seconds" "$transcript"
        else
            printf '%s\t%s\n' "$iteration" "$seconds" >> "$BENCH_LOG"
            printf 'Run %s:  %ss — %s\n' "$iteration" "$seconds" "$transcript"
        fi
    done

    local metrics
    metrics="$(python3 - "$BENCH_LOG" <<'PY'
import math
import pathlib
import statistics
import sys

values = [float(line.split("\t")[1]) for line in pathlib.Path(sys.argv[1]).read_text().splitlines()]
ordered = sorted(values)
p95 = ordered[max(0, math.ceil(0.95 * len(ordered)) - 1)]
print(f"p50={statistics.median(values):.3f}s p95={p95:.3f}s min={min(values):.3f}s max={max(values):.3f}s")
PY
)"

    if grep -Eqi 'cuda|nvidia' "$SERVER_LOG"; then
        record_result "cuda-backend" "PASS" "whisper.cpp log reports CUDA/NVIDIA initialization"
    else
        record_result "cuda-backend" "WARN" "CUDA was not evident in the server log"
    fi

    local p95
    p95="$(python3 - "$BENCH_LOG" <<'PY'
import math
import pathlib
import sys
values = sorted(float(line.split("\t")[1]) for line in pathlib.Path(sys.argv[1]).read_text().splitlines())
print(values[max(0, math.ceil(0.95 * len(values)) - 1)])
PY
)"
    if python3 - "$p95" <<'PY'
import sys
raise SystemExit(0 if float(sys.argv[1]) <= 3.0 else 1)
PY
    then
        record_result "warm-asr" "PASS" "$metrics"
    else
        record_result "warm-asr" "FAIL" "$metrics (p95 exceeds 3 seconds)"
    fi
    end_to_end_benchmark "$port" || {
        stop_server
        return 1
    }
    stop_server
}

clipboard_fallback() {
    local test_text="$1"
    local previous="$RUNTIME_DIR/clipboard.previous"
    local current="$RUNTIME_DIR/clipboard.current"
    local had_previous=0

    if wl-paste --no-newline > "$previous" 2>/dev/null; then
        had_previous=1
    else
        : > "$previous"
    fi

    printf '%s' "$test_text" | wl-copy
    wtype -M ctrl v -m ctrl
    sleep 0.3
    wl-paste --no-newline > "$current" 2>/dev/null || : > "$current"

    if cmp -s "$current" <(printf '%s' "$test_text"); then
        if ((had_previous)); then
            wl-copy < "$previous"
        else
            wl-copy --clear
        fi
        return 0
    fi

    printf 'Clipboard changed concurrently; preserving the newer clipboard instead of restoring.\n'
    return 0
}

test_one_application() {
    local app="$1"
    local safe_text=$'# Yap Linux spike ✓ — café\n# second line: 你好 مرحبا'

    section "Insertion: $app"
    printf 'Open an editable, non-password field in %s.\n' "$app"
    printf 'Press Enter here, then focus that field within five seconds.\n'
    read -r
    sleep 5
    printf '%s' "$safe_text" | wtype -d 1 -
    printf '\nReturn here. Did direct virtual-keyboard insertion preserve Unicode and both lines? [y/n/s] '
    read -r direct_answer
    case "$direct_answer" in
        y|Y) record_result "insert-$app" "PASS" "Direct virtual-keyboard insertion"; return 0 ;;
        s|S) record_result "insert-$app" "SKIP" "Not tested"; return 0 ;;
    esac

    printf 'Testing clipboard + synthetic Ctrl-V fallback.\n'
    printf 'Press Enter, then focus the same field within five seconds.\n'
    read -r
    sleep 5
    clipboard_fallback "$safe_text"
    printf '\nReturn here. Did the clipboard fallback preserve Unicode and both lines? [y/N] '
    read -r clipboard_answer
    if [[ "$clipboard_answer" =~ ^[Yy]$ ]]; then
        record_result "insert-$app" "PASS" "Clipboard fallback"
    else
        record_result "insert-$app" "FAIL" "Direct and clipboard insertion failed"
    fi
}

insertion_matrix() {
    local applications=(Firefox VS-Code-or-Electron Kitty GTK-reference Qt-reference XWayland-reference)
    local app
    for app in "${applications[@]}"; do
        test_one_application "$app"
    done
}

report() {
    section "Shareable spike report"
    printf 'Yap Linux / Hyprland prototype\n'
    printf 'Generated: %s\n' "$(date --iso-8601=seconds)"
    printf 'Session: %s / %s\n' "${XDG_SESSION_TYPE:-unknown}" "${XDG_CURRENT_DESKTOP:-unknown}"
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl version 2>/dev/null | sed -n '1,3p' || true
    fi
    if command -v nvidia-smi >/dev/null 2>&1; then
        nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv,noheader 2>/dev/null || true
    fi
    printf '\nResults:\n'
    if [[ -s "$RESULT_LOG" ]]; then
        column -t -s $'\t' "$RESULT_LOG" 2>/dev/null || cat "$RESULT_LOG"
    else
        printf 'No results recorded.\n'
    fi
    if [[ -s "$SERVER_LOG" ]]; then
        printf '\nInference backend evidence:\n'
        grep -Ei 'cuda|nvidia|gpu|backend|model load|load time' "$SERVER_LOG" | tail -n 30 || true
    fi
    printf '\nScratch artifacts: %s\n' "$RUNTIME_DIR"
}

cleanup() {
    section "Prototype cleanup"
    printf 'This removes only:\n  %s\n  %s\n' "$RUNTIME_DIR" "$HOTKEY_CONFIG"
    printf 'It keeps the downloaded model at %s.\n' "$MODEL_FILE"
    read -r -p 'Continue? [y/N] ' answer
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
        return 0
    fi
    stop_children
    rm -f "$RUNTIME_DIR"/* 2>/dev/null || true
    rmdir "$RUNTIME_DIR" 2>/dev/null || true
    rm -f "$HOTKEY_CONFIG"
    printf 'Remove the corresponding source line from hyprland.conf, then reload Hyprland.\n'
}

guided() {
    printf '\n\033[1mYap Linux / Hyprland feasibility spike\033[0m\n'
    printf 'PROTOTYPE ONLY. No production files are installed.\n'
    doctor || return 1
    generate_hotkey_config
    printf '\nAfter sourcing the generated file and reloading Hyprland, press Enter.\n'
    read -r
    test_hotkey || return 1
    ensure_model || return 1
    capture_audio || return 1
    benchmark || return 1
    insertion_matrix
    report
}

usage() {
    cat <<EOF
Usage: $0 [command]

Commands:
  guided       Run the complete interactive spike (default)
  doctor       Inspect the Hyprland, portal, audio, model, and tool environment
  setup        Generate the Right Super Hyprland binding snippet
  hotkey       Test three Right Super press/release pairs
  model        Explicitly download and verify the prototype ASR model
  capture      Record a scratch 16 kHz mono WAV through PipeWire
  benchmark    Benchmark five warm whisper.cpp requests
  insertion    Run the manual Wayland/XWayland insertion matrix
  report       Print the shareable evidence report
  state        Show accumulated prototype state
  cleanup      Remove scratch state and the generated Hyprland snippet
EOF
}

trap stop_children EXIT INT TERM

case "${1:-guided}" in
    guided) guided ;;
    doctor) doctor; show_state ;;
    setup) generate_hotkey_config; show_state ;;
    hotkey) test_hotkey; show_state ;;
    model) ensure_model; show_state ;;
    capture) capture_audio; show_state ;;
    benchmark) benchmark; show_state ;;
    insertion) insertion_matrix; show_state ;;
    report) report ;;
    state) show_state ;;
    cleanup) cleanup ;;
    help|-h|--help) usage ;;
    *) usage; exit 2 ;;
esac
