#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13
EXPECTED_VERSION="0.0.12"
REPORT_ROOT="${XDG_STATE_HOME:-$HOME/.local/state}/yap"
REPORT_FILE="$REPORT_ROOT/linux-acceptance-$EXPECTED_VERSION-$(date +%Y%m%dT%H%M%S).md"
FAILED=0
CPU_OVERRIDE_ACTIVE=0
PATH_OVERRIDE_ACTIVE=0
ORIGINAL_MANAGER_PATH=""
MANAGER_PATH_WAS_SET=0
TEMP_BIN=""
XDG_DATA_OVERRIDE_ACTIVE=0
ORIGINAL_MANAGER_XDG_DATA_HOME=""
MANAGER_XDG_DATA_HOME_WAS_SET=0
CLEAN_DATA_ROOT=""

install -d -m 700 "$REPORT_ROOT"
umask 077
printf '# Yap Linux %s acceptance\n\n- Started: %s\n- Result: INCOMPLETE\n\n' \
  "$EXPECTED_VERSION" "$(date --iso-8601=seconds)" > "$REPORT_FILE"

record() {
  printf '%s\n' "$1" >> "$REPORT_FILE"
}

section() {
  printf '\n## %s\n' "$1" >> "$REPORT_FILE"
}

pass_gate() {
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  record "- PASS: $1"
}

fail_gate() {
  printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
  record "- FAIL: $1"
  FAILED=$((FAILED + 1))
}

human_gate() {
  if confirm "$1"; then
    pass_gate "$1"
  else
    fail_gate "$1"
  fi
}

command_gate() {
  local label="$1"
  shift
  if "$@"; then
    pass_gate "$label"
  else
    fail_gate "$label"
  fi
}

restore_overrides() {
  if (( PATH_OVERRIDE_ACTIVE )); then
    if (( MANAGER_PATH_WAS_SET )); then
      systemctl --user set-environment "PATH=$ORIGINAL_MANAGER_PATH" >/dev/null 2>&1 || true
    else
      systemctl --user unset-environment PATH >/dev/null 2>&1 || true
    fi
    PATH_OVERRIDE_ACTIVE=0
  fi
  if (( CPU_OVERRIDE_ACTIVE )); then
    systemctl --user unset-environment YAP_FORCE_CPU >/dev/null 2>&1 || true
    CPU_OVERRIDE_ACTIVE=0
  fi
  if (( XDG_DATA_OVERRIDE_ACTIVE )); then
    pkill -TERM -f '/usr/bin/yap-ui' >/dev/null 2>&1 || true
    if (( MANAGER_XDG_DATA_HOME_WAS_SET )); then
      systemctl --user set-environment \
        "XDG_DATA_HOME=$ORIGINAL_MANAGER_XDG_DATA_HOME" >/dev/null 2>&1 || true
    else
      systemctl --user unset-environment XDG_DATA_HOME >/dev/null 2>&1 || true
    fi
    XDG_DATA_OVERRIDE_ACTIVE=0
  fi
  if [[ -n "$TEMP_BIN" && -d "$TEMP_BIN" ]]; then
    rm -f "$TEMP_BIN/wtype" "$TEMP_BIN/pw-record"
    rmdir "$TEMP_BIN" 2>/dev/null || true
  fi
  systemctl --user restart yap.service >/dev/null 2>&1 || true
  if [[ -n "$CLEAN_DATA_ROOT" && "$CLEAN_DATA_ROOT" == "$REPORT_ROOT"/clean-onboarding.* ]]; then
    rm -rf -- "$CLEAN_DATA_ROOT"
    CLEAN_DATA_ROOT=""
  fi
}

abort_wizard() {
  restore_overrides
  trap - EXIT INT TERM
  exit 130
}

trap restore_overrides EXIT
trap abort_wizard INT TERM

banner "Yap Linux 0.0.12 release acceptance"

stage "Production candidate preflight"
say "This run qualifies the checksummed production package, not PKGBUILD.dev."
record "## Production candidate preflight"
command_gate "yap-dictation production package is installed" pacman -Q yap-dictation
command_gate "yap reports version $EXPECTED_VERSION" bash -c '[[ "$(yap --version)" == "yap 0.0.12" ]]'
command_gate "yapctl reports version $EXPECTED_VERSION" bash -c '[[ "$(yapctl --version)" == "yapctl 0.0.12" ]]'
command_gate "Wayland session is active" bash -c '[[ "${XDG_SESSION_TYPE:-}" == "wayland" ]]'
command_gate "Hyprland is reachable" hyprctl version
record "- Branch head: $(git rev-parse --short HEAD 2>/dev/null || printf unknown)"
record "- Kernel: $(uname -srmo)"
record "- Desktop: ${XDG_CURRENT_DESKTOP:-unknown}"
if (( FAILED )); then
  warn "Preflight failed. Install the current production PKGBUILD and re-run this wizard."
  note "From Linux/packaging/arch: makepkg -p PKGBUILD --syncdeps --install --cleanbuild --clean --force"
  note "Evidence so far: $REPORT_FILE"
  exit 1
fi
pause "Preflight is clean. Press Enter for model and service setup."

stage "Models, health, and user services"
section "Models, health, and user services"
say "The installer verifies both pinned local models; existing valid files are reused."
command_gate "Both pinned models install or verify successfully" yap model install
command_gate "Hyprland user services set up successfully" yap setup hyprland
command_gate "yap doctor reports a runnable machine" yap doctor
for unit in yap.service yap-overlay.service yap-tray.service; do
  command_gate "$unit is enabled" systemctl --user is-enabled --quiet "$unit"
  command_gate "$unit is active" systemctl --user is-active --quiet "$unit"
done
command_gate "Daemon answers on D-Bus" yapctl status
pause "Press Enter after reviewing the doctor output above."

stage "Dashboard and tray"
section "Dashboard and tray"
say "Yap will open its GTK dashboard. Exercise every sidebar page and the tray menu."
command_gate "Dashboard process launches" yap gui
step "Confirm Overview shows Ready and the complete health list is readable."
step "Open Settings, History, and Snippets; resize and scroll the window."
step "Use the tray to open status/settings/history/snippets, then restart Yap."
human_gate "Dashboard navigation, controls, and layout work without errors"
human_gate "Tray is visible and every menu action targets the expected surface"
command_gate "Services remain active after the tray restart" systemctl --user is-active --quiet yap.service yap-overlay.service yap-tray.service

stage "Hyprland gestures and overlay"
section "Hyprland gestures and overlay"
say "Use your own configured Dictation binding; do not invoke yapctl manually in this stage."
step "Quick-tap and release: no recording should survive and no text should appear."
step "Hold, speak, release: the pill should show recording, processing, then disappear."
step "Double-tap: the pill should lock; speak, then press once to stop."
step "Repeat on another workspace and in another app while watching keyboard focus."
human_gate "Quick-tap cancellation produces no text"
human_gate "Hold-to-dictate inserts text and shows a live audio-driven waveform"
human_gate "Double-tap hands-free lock and the next-press stop gesture work"
human_gate "Overlay follows workspaces, shows recording/locked/processing, and never steals focus"
command_gate "Daemon returns to idle after gesture tests" bash -c 'yapctl status | grep -Fx "phase: idle"'

stage "Insertion and clipboard fallback"
section "Insertion and clipboard fallback"
say "First validate normal direct insertion and clipboard preservation."
step "Copy a harmless sentinel, dictate multiline text containing café, naïve, and an emoji, then paste the clipboard elsewhere."
human_gate "Multiline and non-ASCII text insert correctly and the prior clipboard is preserved"
say "The wizard will now force only direct wtype input to fail, exercising Yap's real clipboard fallback."
ORIGINAL_MANAGER_PATH=$(systemctl --user show-environment | sed -n 's/^PATH=//p' | head -n1)
if [[ -n "$ORIGINAL_MANAGER_PATH" ]]; then
  MANAGER_PATH_WAS_SET=1
else
  ORIGINAL_MANAGER_PATH="$PATH"
fi
TEMP_BIN=$(mktemp -d "${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR is required}/yap-acceptance-bin.XXXXXX")
cat > "$TEMP_BIN/wtype" <<'WRAPPER'
#!/usr/bin/env bash
if [[ "$#" -eq 3 && "$1" == "-d" && "$2" == "1" && "$3" == "-" ]]; then
  cat >/dev/null
  exit 64
fi
exec /usr/bin/wtype "$@"
WRAPPER
chmod 700 "$TEMP_BIN/wtype"
systemctl --user set-environment "PATH=$TEMP_BIN:$ORIGINAL_MANAGER_PATH"
PATH_OVERRIDE_ACTIVE=1
systemctl --user restart yap.service
step "Dictate one short sentence into an editor; it should appear through the clipboard fallback."
human_gate "Forced clipboard fallback inserts text and restores the previous clipboard"
if (( MANAGER_PATH_WAS_SET )); then
  systemctl --user set-environment "PATH=$ORIGINAL_MANAGER_PATH"
else
  systemctl --user unset-environment PATH
fi
PATH_OVERRIDE_ACTIVE=0
systemctl --user restart yap.service
rm -f "$TEMP_BIN/wtype"
rmdir "$TEMP_BIN"
TEMP_BIN=""

stage "Cleanup, courtesy, and application tone"
section "Cleanup, courtesy, and application tone"
say "Use Dashboard → Settings and save each requested value before dictating."
step "Test cleanup Off, Light, Medium, High, and Max with the same rambling sentence."
step "Toggle courtesy trimming and verify leading/trailing courtesy is removed only when enabled."
step "With cleanup enabled, compare output in an email app, chat app, terminal/editor, and notes app."
human_gate "All five cleanup levels persist and produce sensible increasing cleanup"
human_gate "Courtesy trimming is predictable and preserves meaningful sentences"
human_gate "Email, chat, code, and notes contexts receive appropriate local tone"

stage "Snippets and history"
section "Snippets and history"
say "Use the dashboard's Snippets and History pages."
step "Create a snippet with spoken trigger résumé and a distinctive expansion. Dictate RÉSUMÉ."
step "Verify the expansion occurs as a whole phrase, but not inside my_résumé. Edit it, retest, then delete it."
step "Verify successful dictations appear newest-first in History, Copy works, and Clear removes them."
step "Restart yap.service and confirm retained entries/settings survive before clearing."
human_gate "Snippet create/edit/delete, Unicode case matching, and underscore boundaries work"
human_gate "History is newest-first, copyable, clearable, and persists across restart"

stage "Command Mode"
section "Command Mode"
say "Use your own Command Mode press/release binding."
step "With no selection, ask for a short piece of text; it should be generated at the cursor."
step "Select a paragraph, ask to make it concise, and verify only the selection is replaced."
step "Keep a harmless clipboard sentinel before both operations and verify it is restored afterward."
step "Confirm Command Mode output is not added to dictation history."
human_gate "Command Mode generates at the cursor without a selection"
human_gate "Command Mode transforms and replaces selected text"
human_gate "Selection capture restores the clipboard and Command Mode does not pollute history"

stage "PipeWire playback policies and cancellation"
section "PipeWire playback policies and cancellation"
say "Start media playback and use Dashboard → Settings for each policy."
step "Off: playback and volume must remain untouched during dictation."
step "Lower: choose a visible target; volume must lower during capture and restore exactly afterward."
step "Pause: active playback must pause, then resume; content already paused by you must stay paused."
human_gate "Off, Lower, and Pause behave correctly and restore exact prior playback state"
say "Now start media playback and double-tap Dictation so recording is locked."
pause "Press Enter while the locked recording is active; the wizard will restart yap.service."
systemctl --user restart yap.service
pause "Confirm playback state has recovered, then press Enter."
human_gate "Mid-recording service restart restores audio state and leaves Yap usable"
command_gate "No captured WAV remains after cancellation" bash -c '[[ -z "$(find "$XDG_RUNTIME_DIR/yap" -maxdepth 1 -type f -name "*.wav" -print -quit)" ]]'

stage "Privacy canary and error state"
section "Privacy canary and error state"
say "Choose a unique harmless phrase. It is held only in this process and is never written to the report."
PRIVACY_CANARY=""
while [[ -z "$PRIVACY_CANARY" ]]; do
  ask_secret PRIVACY_CANARY "Enter the non-empty unique phrase, then dictate it once:"
done
pause "Press Enter after insertion has completed and History shows the successful dictation."
PRIVACY_LEAK=0
if journalctl --user -u yap.service -b --no-pager | grep -Fq -- "$PRIVACY_CANARY"; then
  PRIVACY_LEAK=1
fi
for log in "$XDG_RUNTIME_DIR/yap/whisper-server.log" "$XDG_RUNTIME_DIR/yap/llama-server.log"; do
  if [[ -f "$log" ]] && grep -Fq -- "$PRIVACY_CANARY" "$log"; then
    PRIVACY_LEAK=1
  fi
done
unset PRIVACY_CANARY
if (( PRIVACY_LEAK )); then
  fail_gate "Captured content is absent from service and model-server logs"
else
  pass_gate "Captured content is absent from service and model-server logs"
fi
command_gate "No captured WAV remains after successful processing" bash -c '[[ -z "$(find "$XDG_RUNTIME_DIR/yap" -maxdepth 1 -type f -name "*.wav" -print -quit)" ]]'
say "The wizard will force pw-record to fail once so the real error surface can be inspected safely."
TEMP_BIN=$(mktemp -d "${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR is required}/yap-acceptance-bin.XXXXXX")
cat > "$TEMP_BIN/pw-record" <<'WRAPPER'
#!/usr/bin/env bash
exit 74
WRAPPER
chmod 700 "$TEMP_BIN/pw-record"
systemctl --user set-environment "PATH=$TEMP_BIN:$ORIGINAL_MANAGER_PATH"
PATH_OVERRIDE_ACTIVE=1
systemctl --user restart yap.service
step "Attempt one Dictation and inspect the overlay/dashboard error message."
human_gate "A capture/runtime failure is actionable in the overlay and dashboard"
if (( MANAGER_PATH_WAS_SET )); then
  systemctl --user set-environment "PATH=$ORIGINAL_MANAGER_PATH"
else
  systemctl --user unset-environment PATH
fi
PATH_OVERRIDE_ACTIVE=0
systemctl --user restart yap.service
rm -f "$TEMP_BIN/pw-record"
rmdir "$TEMP_BIN"
TEMP_BIN=""
step "Run one normal Dictation after recovery."
human_gate "The next normal dictation succeeds after the forced capture error"

stage "NVIDIA and forced CPU inference"
section "NVIDIA and forced CPU inference"
say "First validate automatic NVIDIA acceleration for both persistent local model servers."
systemctl --user unset-environment YAP_FORCE_CPU
systemctl --user restart yap.service
command_gate "NVIDIA GPU is visible" nvidia-smi
command_gate "Optional ggml-cuda backend is installed" pacman -Q ggml-cuda
step "Run one cleaned dictation and one Command Mode transformation."
pause "Press Enter when both NVIDIA-backed operations have completed."
command_gate "Whisper log records CUDA" grep -Eqi 'CUDA|use gpu[[:space:]]*=[[:space:]]*1' "$XDG_RUNTIME_DIR/yap/whisper-server.log"
command_gate "Language-model log records GPU offload" grep -Eqi 'CUDA|offload|GPU' "$XDG_RUNTIME_DIR/yap/llama-server.log"
command_gate "A Yap model server is visible to nvidia-smi" bash -c 'nvidia-smi --query-compute-apps=process_name --format=csv,noheader | grep -Eq "whisper-server|llama-server"'
say "Now both servers will be restarted with the supported CPU-only override."
systemctl --user set-environment YAP_FORCE_CPU=1
CPU_OVERRIDE_ACTIVE=1
systemctl --user restart yap.service
step "Run one dictation and one Command Mode transformation; slower processing is expected."
pause "Press Enter when both forced-CPU operations have completed."
command_gate "Whisper is explicitly CPU-only" grep -Eq 'use gpu[[:space:]]*=[[:space:]]*0' "$XDG_RUNTIME_DIR/yap/whisper-server.log"
command_gate "Language model is configured with zero GPU layers" grep -Eq 'n-gpu-layers[^0-9]*0|offloaded 0/' "$XDG_RUNTIME_DIR/yap/llama-server.log"
human_gate "Dictation and Command Mode both complete successfully on forced CPU"
systemctl --user unset-environment YAP_FORCE_CPU
CPU_OVERRIDE_ACTIVE=0
systemctl --user restart yap.service

stage "Clean first-run onboarding and model download"
section "Clean first-run onboarding and model download"
say "This stage uses a wizard-owned XDG data directory; your real settings, models, snippets, and history are untouched."
ORIGINAL_MANAGER_XDG_DATA_HOME=$(systemctl --user show-environment | sed -n 's/^XDG_DATA_HOME=//p' | head -n1)
if [[ -n "$ORIGINAL_MANAGER_XDG_DATA_HOME" ]]; then
  MANAGER_XDG_DATA_HOME_WAS_SET=1
fi
CLEAN_DATA_ROOT=$(mktemp -d "$REPORT_ROOT/clean-onboarding.XXXXXX")
CLEAN_DATA_HOME="$CLEAN_DATA_ROOT/data"
install -d -m 700 "$CLEAN_DATA_HOME"
systemctl --user set-environment "XDG_DATA_HOME=$CLEAN_DATA_HOME"
XDG_DATA_OVERRIDE_ACTIVE=1
systemctl --user restart yap.service yap-overlay.service yap-tray.service
if XDG_DATA_HOME="$CLEAN_DATA_HOME" yap doctor --json | grep -Fq '"compatibility": "setup_required"'; then
  pass_gate "Fresh data state is recognized as requiring model setup"
else
  fail_gate "Fresh data state is recognized as requiring model setup"
fi
pkill -TERM -f '/usr/bin/yap-ui' >/dev/null 2>&1 || true
XDG_DATA_HOME="$CLEAN_DATA_HOME" yap gui
step "Confirm Overview explains the missing models, shows disk use, and offers Install local models."
step "Click Install local models and wait for both the 547 MiB speech model and 2.33 GiB language model to verify."
pause "Press Enter only after the dashboard reports that both models are ready."
command_gate "Fresh GUI-installed models pass doctor" env XDG_DATA_HOME="$CLEAN_DATA_HOME" yap doctor
systemctl --user restart yap.service
step "Using the fresh defaults, run one Dictation and one Command Mode transformation."
human_gate "Fresh onboarding, complete model download, Dictation, and Command Mode all succeed"
SPEECH_MODEL_FILE="$CLEAN_DATA_HOME/yap/models/large-v3-turbo-q5_0/394221709cd5ad1f40c46e6031ca61bce88931e6e088c188294c6d5a55ffa7e2/ggml-large-v3-turbo-q5_0.bin"
if [[ -f "$SPEECH_MODEL_FILE" ]]; then
  systemctl --user stop yap.service
  printf '\0' | dd of="$SPEECH_MODEL_FILE" bs=1 seek=0 conv=notrunc status=none
  systemctl --user start yap.service
  step "The wizard corrupted only its isolated speech-model copy. Confirm the dashboard reports attention, then click Verify or repair local models."
  pause "Press Enter after the 547 MiB speech model has been repaired and verified."
  systemctl --user restart yap.service
  command_gate "Corrupt isolated speech model repairs successfully" env XDG_DATA_HOME="$CLEAN_DATA_HOME" yap doctor
else
  fail_gate "Fresh speech model exists for the isolated repair test"
fi
pkill -TERM -f '/usr/bin/yap-ui' >/dev/null 2>&1 || true
if (( MANAGER_XDG_DATA_HOME_WAS_SET )); then
  systemctl --user set-environment "XDG_DATA_HOME=$ORIGINAL_MANAGER_XDG_DATA_HOME"
else
  systemctl --user unset-environment XDG_DATA_HOME
fi
XDG_DATA_OVERRIDE_ACTIVE=0
systemctl --user restart yap.service yap-overlay.service yap-tray.service
rm -rf -- "$CLEAN_DATA_ROOT"
CLEAN_DATA_ROOT=""
command_gate "Original Yap data and services recover after isolated onboarding" yap doctor
human_gate "Original settings, snippets, and history are present after restoring the real data home"

stage "Package lifecycle and README walkthrough"
section "Package lifecycle and README walkthrough"
say "This final gate tests uninstall/reinstall while preserving private user data."
human_gate "The root README install, binding, usage, privacy, update, troubleshooting, and uninstall instructions are accurate"
human_gate "The prior development-package to yap-dictation installation behaved as a clean package upgrade"
if confirm "Run the real disable, uninstall, and local production-package reinstall now?"; then
  PACKAGE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../Linux/packaging/arch" && pwd)
  PACKAGE_FILE=$(cd "$PACKAGE_DIR" && makepkg --packagelist | grep '/yap-dictation-[^-]*-[^-]*-x86_64\.pkg\.tar\.' | head -n1 || true)
  if [[ -z "$PACKAGE_FILE" || ! -f "$PACKAGE_FILE" ]]; then
    fail_gate "Built production package archive is available for reinstall"
  else
    DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/yap"
    DATA_MARKER=0
    [[ -d "$DATA_DIR" ]] && DATA_MARKER=1
    REMOVE_PACKAGES=(yap-dictation)
    if pacman -Qq yap-dictation-debug >/dev/null 2>&1; then
      REMOVE_PACKAGES+=(yap-dictation-debug)
    fi
    command_gate "All Yap services disable cleanly" systemctl --user disable --now yap.service yap-overlay.service yap-tray.service
    if sudo pacman -R --noconfirm "${REMOVE_PACKAGES[@]}"; then
      pass_gate "Production package uninstalls cleanly"
      if (( DATA_MARKER )) && [[ -d "$DATA_DIR" ]]; then
        pass_gate "Package uninstall preserves private Yap data"
      elif (( DATA_MARKER )); then
        fail_gate "Package uninstall preserves private Yap data"
      else
        pass_gate "Package uninstall leaves the absent data directory untouched"
      fi
      if sudo pacman -U --noconfirm "$PACKAGE_FILE"; then
        pass_gate "Production package reinstalls from the built archive"
        command_gate "Hyprland setup recovers after reinstall" yap setup hyprland
        command_gate "Reinstalled package reports version $EXPECTED_VERSION" bash -c '[[ "$(yap --version)" == "yap 0.0.12" ]]'
        command_gate "Reinstalled package passes doctor" yap doctor
        command_gate "All three services recover after reinstall" systemctl --user is-active --quiet yap.service yap-overlay.service yap-tray.service
        human_gate "A post-reinstall dictation succeeds with prior settings/models intact"
      else
        fail_gate "Production package reinstalls from the built archive"
        warn "Direct reinstall failed; attempting dependency-aware makepkg recovery."
        if (cd "$PACKAGE_DIR" && makepkg -p PKGBUILD --syncdeps --install --noconfirm); then
          pass_gate "Dependency-aware package recovery succeeds"
          command_gate "Hyprland setup recovers after package recovery" yap setup hyprland
        else
          fail_gate "Dependency-aware package recovery succeeds"
        fi
      fi
    else
      fail_gate "Production package uninstalls cleanly"
      command_gate "Services recover after the declined uninstall" yap setup hyprland
    fi
  fi
else
  fail_gate "Disable/uninstall/reinstall lifecycle was exercised"
fi

restore_overrides
trap - EXIT INT TERM
record ""
record "- Finished: $(date --iso-8601=seconds)"
if (( FAILED == 0 )); then
  sed -i 's/- Result: INCOMPLETE/- Result: PASS/' "$REPORT_FILE"
  finish
  printf '  %s%sAll Linux 0.0.12 acceptance gates passed.%s\n' "$BOLD" "$GREEN" "$RESET"
  printf '  Evidence report: %s\n\n' "$REPORT_FILE"
  exit 0
fi

sed -i "s/- Result: INCOMPLETE/- Result: FAIL ($FAILED gate(s))/" "$REPORT_FILE"
_clear
printf '\n%s%s  Release remains blocked%s\n' "$BOLD" "$RED" "$RESET"
printf '  %s gate(s) failed or were declined.\n' "$FAILED"
printf '  Evidence report: %s\n\n' "$REPORT_FILE"
exit 1
